services:
  robot_1:
    command: bash -c "colcon build && . ./install/setup.sh && ros2 launch gcnsched_demo node1_launch.py"
    environment:
      PYTHONUNBUFFERED: 1
    image: smile_ros
    volumes:
    - /workspace/gcnschedule-turtlenet/.workspaces/robot_1:/workspace
    - /workspace/gcnschedule-turtlenet/src:/workspace/src:ro
  robot_2:
    command: bash -c "colcon build && . ./install/setup.sh && ros2 launch gcnsched_demo node2_launch.py"
    environment:
      PYTHONUNBUFFERED: 1
    image: smile_ros
    volumes:
    - /workspace/gcnschedule-turtlenet/.workspaces/robot_2:/workspace
    - /workspace/gcnschedule-turtlenet/src:/workspace/src:ro
  robot_3:
    command: bash -c "colcon build && . ./install/setup.sh && ros2 launch gcnsched_demo node3_launch.py"
    environment:
      PYTHONUNBUFFERED: 1
    image: smile_ros
    volumes:
    - /workspace/gcnschedule-turtlenet/.workspaces/robot_3:/workspace
    - /workspace/gcnschedule-turtlenet/src:/workspace/src:ro
  robot_4:
    command: bash -c "colcon build && . ./install/setup.sh && ros2 launch gcnsched_demo node4_launch.py"
    environment:
      PYTHONUNBUFFERED: 1
    image: smile_ros
    volumes:
    - /workspace/gcnschedule-turtlenet/.workspaces/robot_4:/workspace
    - /workspace/gcnschedule-turtlenet/src:/workspace/src:ro
  rosboard:
    command: bash -c "colcon build && . ./install/setup.sh && /rosboard/run"
    environment:
      PYTHONUNBUFFERED: 1
    image: rosboard
    ports:
    - 9999:8888
    volumes:
    - /workspace/gcnschedule-turtlenet/.workspaces/rosboard:/workspace
    - /workspace/gcnschedule-turtlenet/src:/workspace/src:ro
  scheduler:
    command: bash -c "pip3 install -e /edGNN && colcon build && . ./install/setup.sh && ros2 launch gcnsched_demo sched_launch.py"
    environment:
      PYTHONUNBUFFERED: 1
    image: smile_ros
    volumes:
    - /workspace/gcnschedule-turtlenet/.workspaces/scheduler:/workspace
    - /workspace/gcnschedule-turtlenet/src:/workspace/src:ro
    - ./edGNN:/edGNN
version: '3'
